# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from grpc_generated import worker_pb2 as worker__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in worker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterWorker = channel.unary_unary(
                '/worker.WorkerService/RegisterWorker',
                request_serializer=worker__pb2.RegisterWorkerRequest.SerializeToString,
                response_deserializer=worker__pb2.RegisterWorkerResponse.FromString,
                _registered_method=True)
        self.HeartbeatWorker = channel.unary_unary(
                '/worker.WorkerService/HeartbeatWorker',
                request_serializer=worker__pb2.HeartbeatWorkerRequest.SerializeToString,
                response_deserializer=worker__pb2.HeartbeatWorkerResponse.FromString,
                _registered_method=True)
        self.PullJob = channel.unary_unary(
                '/worker.WorkerService/PullJob',
                request_serializer=worker__pb2.PullJobRequest.SerializeToString,
                response_deserializer=worker__pb2.PullJobResponse.FromString,
                _registered_method=True)
        self.ReportJobResult = channel.unary_unary(
                '/worker.WorkerService/ReportJobResult',
                request_serializer=worker__pb2.ReportJobResultRequest.SerializeToString,
                response_deserializer=worker__pb2.ReportJobResultResponse.FromString,
                _registered_method=True)


class WorkerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterWorker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HeartbeatWorker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PullJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportJobResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorker,
                    request_deserializer=worker__pb2.RegisterWorkerRequest.FromString,
                    response_serializer=worker__pb2.RegisterWorkerResponse.SerializeToString,
            ),
            'HeartbeatWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.HeartbeatWorker,
                    request_deserializer=worker__pb2.HeartbeatWorkerRequest.FromString,
                    response_serializer=worker__pb2.HeartbeatWorkerResponse.SerializeToString,
            ),
            'PullJob': grpc.unary_unary_rpc_method_handler(
                    servicer.PullJob,
                    request_deserializer=worker__pb2.PullJobRequest.FromString,
                    response_serializer=worker__pb2.PullJobResponse.SerializeToString,
            ),
            'ReportJobResult': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportJobResult,
                    request_deserializer=worker__pb2.ReportJobResultRequest.FromString,
                    response_serializer=worker__pb2.ReportJobResultResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'worker.WorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('worker.WorkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/worker.WorkerService/RegisterWorker',
            worker__pb2.RegisterWorkerRequest.SerializeToString,
            worker__pb2.RegisterWorkerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HeartbeatWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/worker.WorkerService/HeartbeatWorker',
            worker__pb2.HeartbeatWorkerRequest.SerializeToString,
            worker__pb2.HeartbeatWorkerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PullJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/worker.WorkerService/PullJob',
            worker__pb2.PullJobRequest.SerializeToString,
            worker__pb2.PullJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportJobResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/worker.WorkerService/ReportJobResult',
            worker__pb2.ReportJobResultRequest.SerializeToString,
            worker__pb2.ReportJobResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
